### PR TITLE
JBEAP-20756

### PR DESCRIPTION
**Pull request by tadamski**
@fl4via Could you please review?

### CODE REVIEW

**Comment by fl4via** [comment]
Sure, @tadamski ! I have just looked at the commits, and they seem fine. Still, I'm also going to review the Jiras to entirely refresh my memory before giving my final okay, just to make sure I'm not missing anything.

**Comment by tadamski** [comment]
thanks @fl4via!

**Comment by TomasHofman** [comment]
Hello @tadamski @fl4via , did you manage to review, so this can be merged?

(These commits were/are released in EAP 7.3.6 / 7.4.1 from private branches. According to the usual rules, we would expect them to be ported to this upstream repository, to avoid a situation when a future version of EJB Client is released without these fixes, hence creating a regression if such version gets consumed by a product.)

**Comment by soul2zimate** [comment]
@tadamski  @chengfang  please merge this one in upstream, we need https://github.com/wildfly/jboss-ejb-client/pull/515/commits/5d7f42306bca86c88fbb084012dc57e745892844 this commit present in next jboss-ejb-client upgrade, Thanks.

**Comment by tadamski** [comment]
@TomasHofman @soul2zimate merged

**Pull request merged**
