### PR TITLE
[EJBCLIENT-254] Fix bug where JBossEJBProperties.class.getClassLoader() returned null

### PR DESCRIPTION
**Pull request by jbaesner**
Unfortunately I was not able to provide an automated unittest for this fix, but the Jira issue itself contains the procedure steps to reproduce it...

### CODE REVIEW

**Comment by dmlloyd** [comment]
It would be much better to handle null properly than to fall back to a random, other classloader. Normally we never want to mix classloader acquisition strategies.

**Comment by jbaesner** [comment]
Well, in that case a default 'jboss-ejb-client.properties' inside the jar would not be found, as we wouldn't have a ClassLoader...

**Comment by dmlloyd** [comment]
You do have a class loader. "Null" just means you have to use ClassLoader.getSystemResource() etc. instead.

**Comment by n1hility** [comment]
Take a look at #301

**Pull request closed without merging**
