### PR TITLE
EJBCLIENT-241 Shut down executor service in EJBClientContext

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/JBEAP-8577
https://issues.jboss.org/browse/EJBCLIENT-241

### CODE REVIEW

**Comment by elguardian** [comment]
Aren't you getting rejection execution exception with this change ?

**Comment by TomasHofman** [comment]
So far I didn't notice, I'll do some more experiments. Are you getting those or just suspecting?

**Comment by elguardian** [comment]
I just suspect that could happen... but very edge cases. You should ask David. I remember that the shutdown was there at some point but cannot remember when.

**Comment by TomasHofman** [comment]
I checked the code once more - tasks are submitted to ```ejbClientContextTasksExecutorService``` in methods:
* ```registerEJBReceiver()```
* ```unregisterEJBReceiver()```
* ```attemptReconnections()```

Intuitively I think none of these methods should be called on closed context, apart perhaps from ```unregisterEJBReceiver()```. All ejb receivers are however unregistered in the ```close()``` method, so there's no reason to do that again (but who knows).

https://github.com/jbossas/jboss-eap7/blob/7.0.x/ejb3/src/main/java/org/jboss/as/ejb3/remote/DescriptorBasedEJBClientContextService.java#L117 - here it calls unregister and close in correct orther.

**Comment by elguardian** [comment]
attemptReconnections can be executed at any time... that is the reason you have a close check in the ReconnectHandler... The offending commit about not shuting down is this one:

https://github.com/jbossas/jboss-ejb-client/commit/87aef56ab787f57a9508c6e2b0f876066ae464fe

@bmaxwell can give away more info about why he removed that line

**Comment by TomasHofman** [comment]
Hmm, that looks quite relevant.

**Comment by elguardian** [comment]
I think you can bypass the problem related to execute  tasks avoiding the rejected execution exception. The trick would be to use the RejectedExecutionHandler somethink like this....
`		ThreadPoolExecutor service = (ThreadPoolExecutor) Executors.newCachedThreadPool(new DaemonThreadFactory("ejb-client-context-tasks"));
		service.setRejectedExecutionHandler(new RejectedExecutionHandler() {

			@Override
			public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
				if(executor.isShutdown()) {
					System.out.println("this in theory should not happen");
				}
				r.run();
			}
			
		});`

so even if you shutdown the executor you will execute the task in the caller thread... You can add some stacktrace if you are calling the executor after closing the context.

**Comment by TomasHofman** [comment]
The thing is I didn't manage to reproduce RejectedExecutionHandler at all. It may've been a problem in earlier version which is now fixed.

**Comment by TomasHofman** [comment]
Closing this for now until the other necessary fixes are figured out.

**Pull request closed without merging**
