### PR TITLE
Make project compile on JDK 17 and add JDK 17 to the GH CI workflow

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/JBEAP-22927

### CODE REVIEW

**Comment by xstefank** [comment]
@chengfang passing on hotspot locally, openj9 don't know. Can you please approve the running of actions for this PR?

**Comment by xstefank** [comment]
@chengfang can you please retrigger the actions? Can you help me with which jobs are expected to fail?

**Comment by chengfang** [comment]
all failed jobs seem environmental, and are intermittent failures.  In my local run, they all passed.

**Review by chengfang — APPROVED** [review]

**Comment by xstefank** [comment]
thanks for confirming @chengfang. In that case, I think if this is merged we can resolve the issue.

**Pull request merged**
