### PR TITLE
[WFLY-14668] Eliminated reflection magic - hacking into proxy class internals is forbidden since JDK16

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/WFLY-14680

### CODE REVIEW

**Comment by ropalka** [comment]
@tadamski @rachmatowicz @gaol please review

**Review by tadamski — APPROVED** [review]

**Comment by ropalka** [comment]
Could you merge this PR into master @tadamski , please?
To be in sync with https://github.com/wildfly/jboss-ejb-client/pull/513

**Comment by tadamski** [comment]
@ropalka sure, merged

**Comment by ropalka** [comment]
Thanks @tadamski !

**Pull request merged**
