### PR TITLE
EJBCLIENT-305 Allow to configure maximumConnectedClusterNodes

### PR DESCRIPTION
**Pull request by TomasHofman**
...via wildfly-config.xml and jboss-ejb-client.properties

Issue: https://issues.jboss.org/browse/JBEAP-15448
Upstream issue: https://issues.jboss.org/browse/EJBCLIENT-305
Upstream PR: https://github.com/wildfly/jboss-ejb-client/pull/406

### CODE REVIEW

**Comment by xstefank** [comment]
@tadamski @TomasHofman is on PTO, can you push his branch for this PR so we can get EJB client release out?

**Comment by tadamski** [comment]
@xstefank ok, will do

**Comment by tadamski** [comment]
I'm closing this one as I have rebased and pushed it myself.

**Comment by TomasHofman** [comment]
Thanks for handling this for me @tadamski and @xstefank. (Just an explanation - I made two commits so that it would be visible in git history how the new XSD differed from the old one. I think we use this strategy in Wildfly too, if I'm not mistaken.)

**Pull request closed without merging**
