### PR TITLE
[EJBCLIENT-380] Additional logging for mismatched protocol/port confi…

### PR DESCRIPTION
**Pull request by spyrkob**
…guration

Issue: https://issues.redhat.com/browse/EJBCLIENT-380

Note this PR depends on XNIO change: https://github.com/xnio/xnio/pull/231 and will fail to build without the upgrade.

### CODE REVIEW

**Comment by spyrkob** [comment]
@tadamski could you review when you have a moment please?

**Comment by tadamski** [comment]
@spyrkob merged, thanks
could you please create another one for 4.0 branch?

**Comment by spyrkob** [comment]
@tadamski, I created #467 for 4.0 port.
Just to double check - this PR will not compile without the XNIO changes - should this be merged in before XNIO PR?

**Comment by tadamski** [comment]
@spyrkob yeah, this was my mistake - I will ask Flavia if she could do a XNIO release and will do upgrade on top of that merge; OTOH I will merge 4.0 only after xnio upgrade

**Pull request merged**
